import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "E-commerce Shop",
  description: "Generated by create next app",
};

export default function ServerLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
