import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";


const vazir = Vazirmatn({
  subsets: ["latin", "arabic"],
  variable: "--font-vazirmatn",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],  
});

export const metadata: Metadata = {
  title: "E-commerce Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.variable}>
        
        {children}
      </body>
    </html>
  );
}
