/* eslint-disable react/no-children-prop */
import type { Metadata } from "next";
import {Vazirmatn} from "next/font/google";
import "./globals.css";
import ShopLayout from "./Shop/layout";

const vazir = Vazirmatn({
  subsets: ['latin', 'arabic'],  
  variable: "--font-vazirmatn",
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // وزن‌های قابل استفاده
});


export const metadata: Metadata = {
  title: "E-commerce Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ vazir.variable} antialiased`}
      >
         
        <ShopLayout>
        {children}
        </ShopLayout>
      </body>
    </html>
  );
}
